openapi: 3.0.0
info:
  title: upsider-wala
  version: '1.0'
  contact:
    name: Eiji Mishiro
    email: eiji.346g@confide.jp
  license:
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
    name: Apache 2.0
  description: |
    コーディングテストで利用するスーパー支払い君.comのAPIエンドポイントの仕様を一部まとめたもの
servers:
  - url: 'http://localhost:8080/api'
tags:
  - name: core
    description: coreコンテキストの適応
paths:
  /session:
    post:
      responses:
        '200':
          $ref: "#/components/responses/SignInResponse"
      operationId: signIn
      description: sign in用のエンドポイント
      tags:
        - core
      requestBody:
          $ref: "#/components/requestBodies/SignInRequest"
  /invoices:
    post:
      responses:
        '200':
          $ref: "#/components/responses/CreateInvoiceResponse"
      operationId: createInvoice
      description: 請求書作成用のエンドポイント
      tags:
        - core
      requestBody:
          $ref: "#/components/requestBodies/CreateInvoiceRequest"
components:
  schemas:
  requestBodies:
    CreateInvoiceRequest:
      description: request for creating invoice
      content:
        application/json:
          schema:
            type: object
            properties:
              client_id:
                type: string
                x-oapi-codegen-extra-tags:
                  validate: required
              amount_billed:
                type: integer
                format: int64
                x-oapi-codegen-extra-tags:
                  validate: required
              due_date:
                type: string
                format: date-time
                example: "2006-01-02T15:04:05Z07:00"
                x-oapi-codegen-extra-tags:
                  validate: required
            required:
              - client_id
              - amount_billed
              - due_date
    SignInRequest:
      description: Sign in request
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: string
                x-oapi-codegen-extra-tags:
                  validate: required
              password:
                type: string
                x-oapi-codegen-extra-tags:
                  validate: required
            required:
              - email
              - password
  parameters:
  responses:
    CreateInvoiceResponse:
      description: Sign in response
      content:
        application/json:
          schema:
            type: object
            properties:
              client_id:
                type: string
              amount_billed:
                type: integer
                format: int64
              total_amount:
                type: integer
                format: int64
              due_date:
                type: string
                format: date-time
              issue_date:
                type: string
                format: date-time
              status:
                type: string
            required:
              - client_id
              - amount_billed
              - total_amount
              - due_date
              - issue_date
              - status
    SignInResponse:
      description: Sign in response
      content:
        application/json:
          schema:
            type: object
            properties:
              token:
                type: string
            required:
              - token
