// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ClientBankAccounts string
	Clients            string
	Invoices           string
	Members            string
	Organizations      string
}{
	ClientBankAccounts: "client_bank_accounts",
	Clients:            "clients",
	Invoices:           "invoices",
	Members:            "members",
	Organizations:      "organizations",
}
