output   = "./db/schema"
wipe     = true
no-tests = true

[psql]
  dbname = "postgres"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = ""
  sslmode = "disable"
  blacklist = ["schema_migrations"]
